#-------------------------------
# General Site Settings

title: Gift
logo: 
author: themefisher
description: this is meta description
email: giftabumere247@gmail.com
phone: (+234) 906-788-7538
#address: Kaduna Nigeria
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/coming_soon.html'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Gift <br> A Python Developer

social:
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/gift-abumere-421982215"}
- {icon: "ti-instagram", link: "https://www.instagram.com/gift_dev"}
- {icon: "ti-twitter", link: "https://twitter.com/Gift80402043"}
- {icon: "ti-github", link: "https://github.com/Gift-py"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I've got a lot to learn!! But I'll start with this... totally hyped up!! LFG!!! 😄✨

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "When given a task I ensure to do my 'Homework'. I make extensive research on the task at hand, find the best way to tackle it and draw out my plan on how exactly to tackle this problem as efficiently as possible."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "This is where implementation of the plans takes place. I do everything thing that needs to be done; from data sourcing to algorithm design and implementation (coding) depending on what is needed to solve the task as hand."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "By this time the task at hand is solved and the product has been tested to ensure it works perfectly. Then the product is made to be as user friendly and easy to use as possible before delivering the product."


# My Team Section
#team:
  #- #title : "Jack Schenziwe"
    #image : "assets/images/team/member-1.png"
    #designation : "Project Manager"
    
  #- #title : "Julias Carlie"
    #image : "assets/images/team/member-2.png"
    #designation : "Web Developer"
    
  #- #title : "John Doe"
    #image : "assets/images/team/member-3.png"
    #designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Machine Learning, color: '#fdb157', value: '85%'}
- {name: Data Science, color: '#ffbcaa', value: '70%'}
- {name: Web Design, color: '#9473e6', value: '90%'}
- {name: Web Development (Django), color: '#bdecf6', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Networking and SW-Dev Intern, icon: 'icon-1.png', date: 'Aug 2021 - Nov 2021', organization: 'EARTHLINK'}
- {name: Backend (DJango) Developer, icon: 'icon-2.png', date: 'April 2022 - Present', organization: 'MY EVERY DEAL'}



#-------------------------------
# Education Section

education-title: Education
education:
- {name: B.Sc Computer Science, date: '2024', organization: 'Airforce Institute of Technology'}
#- {name: Secondary School Certificate, date: '2019', organization: 'Christ Ambassadors College'}
#- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
#- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Web Design,
    icon: ti-palette,
    description: 'I can create beautiful UI and UX designs for websites using HTML, CSS and JavaScript',
    active: # Add true to select section
  }
- {
    name: Web Development,
    icon: ti-vector,
    description: 'Capble of creating fully functional web apps with the necessary technologies like python DJango.',
    active: true # Add true to select section
  }
- {
    name: Machine Learning and Data Science,
    icon: ti-panel,
    description: 'develop artificial intelligence (AI) systems that use large data sets to research, develop, and generate algorithms that can learn and make predictions.',
    active: #Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
#portfolio-home-items:
#  - image : "assets/images/portfolio/item-1.png"
#    url: "#"
    
  #- image : "assets/images/portfolio/item-2.png"
  #  url: "#"
    
  #- image : "assets/images/portfolio/item-3.png"
  #  url: "#"
    
  #- image : "assets/images/portfolio/item-4.png"
  #  url: "#"
    
  #- image : "assets/images/portfolio/item-5.png"
  #  url: "#"


# Portfolio Page
#portfolio-label:
#- {
#    title : "UI/UX Design",
#    type : "design"
# }
#- {
#    title : "BRANDING",
#    type : "branding"
#  }
#- {
#    title : "ILLUSTRATION",
#    type : "illustration"
#  }

#portfolio-items:
#  - image : "assets/images/portfolio/item-1.png"
#    url: "#"
#    portfolio-type:
#     - type: "design"
#     - type: "illustration"
#      
#  - image : "assets/images/portfolio/item-2.png"
#    url: "#"
#    portfolio-type:
#      - type: "branding"
#      
#  - image : "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"
#      
#  - image : "assets/images/portfolio/item-6.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      - type: "branding"
#      
#  - image : "assets/images/portfolio/item-8.png"
#   url: "#"
#    portfolio-type:
#      - type: "illustration"
#      
#  - image : "assets/images/portfolio/item-5.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      
#  - image : "assets/images/portfolio/item-1.png"
#    url: "#"
#    portfolio-type:
#      - type: "branding"
#      
#  - image : "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      - type: "illustration"
#      - type: "branding"
#      
#  - image : "assets/images/portfolio/item-7.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"


#-------------------------------
# Testimonials Section

#testimonial-items:
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation : "CEO, Funder"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#    
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#    
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/myevrer.png"
    url: "https://www.instagram.com/myeverydeal/"
    
  - logo: "assets/images/clients-logo/icraft.png"
    url: "#"

  - logo: "assets/images/clients-logo/myevrer.png"
    url: "https://www.instagram.com/myeverydeal/"
    
  - logo: "assets/images/clients-logo/icraft.png"
    url: "#"

  - logo: "assets/images/clients-logo/myevrer.png"
    url: "https://www.instagram.com/myeverydeal/"
    
  - logo: "assets/images/clients-logo/icraft.png"
    url: "#"
    
  #- logo: "assets/images/clients-logo/client-logo-3.png"
  #  url: "#"
    
  #- logo: "assets/images/clients-logo/client-logo-4.png"
  #  url: "#"
    
  #- logo: "assets/images/clients-logo/client-logo-5.png"
  #  url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: giftabumere247@gmail.com
