#-------------------------------
# General Site Settings

title: Gift
logo: 
author: themefisher
description: LOL chicken wings !!!
email: giftabumere247@gmail.com
phone: (+234) 906-788-7538
#address: Kaduna Nigeria
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Articles, link: '/blog'}
- {name: Portfolio, link: '/coming_soon.html'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Gift <br> A Software Engineer 

social:
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/gift-abumere-421982215"}
- {icon: "ti-twitter", link: "https://twitter.com/0xg1f7"}
- {icon: "ti-github", link: "https://github.com/gift-exe"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Hehehe Do you know the way? 

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : ""
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : ""
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : ""


# My Team Section
#team:
  #- #title : "Jack Schenziwe"
    #image : "assets/images/team/member-1.png"
    #designation : "Project Manager"
    
  #- #title : "Julias Carlie"
    #image : "assets/images/team/member-2.png"
    #designation : "Web Developer"
    
  #- #title : "John Doe"
    #image : "assets/images/team/member-3.png"
    #designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Backend Engineering, color: '#bdecf6', value: '90%'}
- {name: ML Engineering, color: '#fdb157', value: '85%'}
- {name: Database Engineering, color: '#9473e6', value: '85%'}
- {name: Dev Ops, color: '#ffbcaa', value: '70%'}
- {name: Network Engineering, color: '#808080', value: '70%'}



#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Network Engineering Intern, icon: 'icon-1.png', date: 'Aug 2021 - Nov 2021', organization: 'EarthLink'}
- {name: Backend Engineer, icon: 'icon-3.png', date: 'April 2022 - August 2022', organization: 'My Every Deal'}
- {name: Backend Engineer, icon: 'icon-2.png', date: 'January 2023 - March 2023', organization: 'NitHub'}
- {name: Backend Engineer, icon: 'icon-3.png', date: 'August 2023 - December 2023', organization: 'Workdistro'}



#-------------------------------
# Education Section

education-title: Education
education:
- {name: B.Sc Computer Science, date: '2024', organization: 'Airforce Institute of Technology'}
- {name: SSCE, date: '2019', organization: 'Christ Ambassadors College'}
#- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
#- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

services-title: Ready to Help You ...
services:
- {
    name: Develop APIs,
    icon: ti-vector,
    description: 'Design, implement, and deploy API services, to optimize business processes',
    active: true # Add true to select section
  }
- {
    name: Develop Machine Learning Applications,
    icon: ti-panel,
    description: 'Develop software systems using state of the art machine learning technologies.',
    active: true #Add true to select section
  }
- {
    name: Build Websites and Mobile Applications,
    icon: ti-palette,
    description: 'Develop and Deploy Websites, Mobile Application using latest technologies',
    active: true # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
#portfolio-home-items:
#  - image : "assets/images/portfolio/item-1.png"
#    url: "#"
    
  #- image : "assets/images/portfolio/item-2.png"
  #  url: "#"
    
  #- image : "assets/images/portfolio/item-3.png"
  #  url: "#"
    
  #- image : "assets/images/portfolio/item-4.png"
  #  url: "#"
    
  #- image : "assets/images/portfolio/item-5.png"
  #  url: "#"


# Portfolio Page
#portfolio-label:
#- {
#    title : "UI/UX Design",
#    type : "design"
# }
#- {
#    title : "BRANDING",
#    type : "branding"
#  }
#- {
#    title : "ILLUSTRATION",
#    type : "illustration"
#  }

#portfolio-items:
#  - image : "assets/images/portfolio/item-1.png"
#    url: "#"
#    portfolio-type:
#     - type: "design"
#     - type: "illustration"
#      
#  - image : "assets/images/portfolio/item-2.png"
#    url: "#"
#    portfolio-type:
#      - type: "branding"
#      
#  - image : "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"
#      
#  - image : "assets/images/portfolio/item-6.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      - type: "branding"
#      
#  - image : "assets/images/portfolio/item-8.png"
#   url: "#"
#    portfolio-type:
#      - type: "illustration"
#      
#  - image : "assets/images/portfolio/item-5.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      
#  - image : "assets/images/portfolio/item-1.png"
#    url: "#"
#    portfolio-type:
#      - type: "branding"
#      
#  - image : "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      - type: "illustration"
#      - type: "branding"
#      
#  - image : "assets/images/portfolio/item-7.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"


#-------------------------------
# Testimonials Section

#testimonial-items:
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation : "CEO, Funder"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#    
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#    
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/myevrer.png"
#     url: "https://www.instagram.com/myeverydeal/"
    
#   - logo: "assets/images/clients-logo/icraft.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/myevrer.png"
#     url: "https://www.instagram.com/myeverydeal/"
    
#   - logo: "assets/images/clients-logo/icraft.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/myevrer.png"
#     url: "https://www.instagram.com/myeverydeal/"
    
#   - logo: "assets/images/clients-logo/icraft.png"
#     url: "#"
    
  #- logo: "assets/images/clients-logo/client-logo-3.png"
  #  url: "#"
    
  #- logo: "assets/images/clients-logo/client-logo-4.png"
  #  url: "#"
    
  #- logo: "assets/images/clients-logo/client-logo-5.png"
  #  url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: giftabumere247@gmail.com
